"""Integration tests using reference disk images generated by BBC Micro emulator.

These tests validate oaknut-dfs functionality against real disk images created by
running BBC BASIC programs on a BBC Micro emulator. Each test class corresponds to
one reference image and verifies the exact content created by its generator program.
"""

import pytest


class TestBasicValidationImage:
    """Tests for 01-basic-validation.ssd (11 files, 3 directories).

    Generator: tests/data/generators/01-basic-validation.bas
    Format: 80-track SSD (204,800 bytes)
    Title: "BASIC TEST"
    """

    @pytest.fixture
    def disk(self, reference_image):
        return reference_image("01-basic-validation.ssd")

    def test_file_count(self, disk):
        """Verify disk contains exactly 11 files."""
        assert len(disk.files) == 11

    def test_disk_title(self, disk):
        """Verify disk title starts with 'BASIC' (stored as 'BASIC' with null padding)."""
        # BBC BASIC *TITLE command stores only first part before space
        assert disk.title.rstrip('\x00') == "BASIC"

    def test_directory_distribution(self, disk):
        """Verify files distributed across $, A, B directories."""
        files_by_dir = {}
        for f in disk.files:
            files_by_dir.setdefault(f.directory, []).append(f.filename)

        assert len(files_by_dir["$"]) == 6  # TEXT, MULTI, X, ABCDEFG, BINARY, LOCKED
        assert len(files_by_dir["A"]) == 3  # DATA1, DATA2, DATA3
        assert len(files_by_dir["B"]) == 2  # FILE1, FILE2

    def test_text_file_content(self, disk):
        """Verify TEXT file contains expected content."""
        content = disk.load("$.TEXT")
        assert content == b"Simple text content"

    def test_multiline_file_content(self, disk):
        """Verify MULTI file has multiple lines with CR+LF."""
        content = disk.load("$.MULTI")
        # BBC BASIC uses CHR$(13)+CHR$(10) for line endings
        expected = b"Line 1\r\nLine 2\r\nLine 3"
        assert content == expected

    def test_single_char_filename(self, disk):
        """Verify single-character filename X exists."""
        assert disk.exists("$.X")
        content = disk.load("$.X")
        assert content == b"Short name"

    def test_max_length_filename(self, disk):
        """Verify 7-character filename ABCDEFG exists."""
        assert disk.exists("$.ABCDEFG")
        entry = disk.get_file_info("$.ABCDEFG")
        assert entry.filename == "ABCDEFG"
        assert len(entry.filename) == 7  # Max allowed
        content = disk.load("$.ABCDEFG")
        assert content == b"Seven character filename test"

    def test_binary_file_content_and_metadata(self, disk):
        """Verify BINARY file has sequential bytes 0-255 and load address 0x2000."""
        entry = disk.get_file_info("$.BINARY")
        assert entry.load_address == 0x2000
        assert entry.exec_address == 0x2000
        assert entry.length == 256

        content = disk.load("$.BINARY")
        assert len(content) == 256
        # Verify sequential bytes 0-255
        assert content == bytes(range(256))

    def test_locked_file_status(self, disk):
        """Verify LOCKED file has locked flag set."""
        assert disk.exists("$.LOCKED")
        entry = disk.get_file_info("$.LOCKED")
        assert entry.locked is True
        content = disk.load("$.LOCKED")
        assert content == b"This file is locked and cannot be deleted"

    def test_directory_a_files(self, disk):
        """Verify directory A contains DATA1, DATA2, DATA3 with correct content."""
        assert disk.exists("A.DATA1")
        assert disk.exists("A.DATA2")
        assert disk.exists("A.DATA3")

        assert disk.load("A.DATA1") == b"Directory A, file 1"
        assert disk.load("A.DATA2") == b"Directory A, file 2"
        assert disk.load("A.DATA3") == b"Directory A, file 3"

    def test_directory_b_files(self, disk):
        """Verify directory B contains FILE1, FILE2 with correct content."""
        assert disk.exists("B.FILE1")
        assert disk.exists("B.FILE2")

        assert disk.load("B.FILE1") == b"Directory B, file 1"
        assert disk.load("B.FILE2") == b"Directory B, file 2"

    def test_all_filenames_present(self, disk):
        """Verify all expected filenames are present."""
        filenames = {f.path for f in disk.files}
        expected = {
            "$.TEXT",
            "$.MULTI",
            "$.X",
            "$.ABCDEFG",
            "$.BINARY",
            "$.LOCKED",
            "A.DATA1",
            "A.DATA2",
            "A.DATA3",
            "B.FILE1",
            "B.FILE2",
        }
        assert filenames == expected


class TestEdgeCasesImage:
    """Tests for 02-edge-cases.ssd (31 files = full catalog).

    Generator: tests/data/generators/02-edge-cases.bas
    Format: 80-track SSD (204,800 bytes)
    Purpose: Test catalog capacity limits and special characters in filenames
    """

    @pytest.fixture
    def disk(self, reference_image):
        return reference_image("02-edge-cases.ssd")

    def test_catalog_full(self, disk):
        """Verify catalog contains maximum 31 files."""
        assert len(disk.files) == 31

    def test_boot_file_with_exclamation(self, disk):
        """Verify !BOOT file exists (! prefix allowed at start)."""
        assert disk.exists("$.!BOOT")
        entry = disk.get_file_info("$.!BOOT")
        assert entry.filename == "!BOOT"

    def test_hyphen_in_filename(self, disk):
        """Verify TEST-1 file exists (hyphen allowed)."""
        assert disk.exists("$.TEST-1")

    def test_file_numbering_sequence(self, disk):
        """Verify FILE0-FILE27, !BOOT, TEST-1, FILE31 naming sequence."""
        # $ directory: FILE0-FILE9, !BOOT, TEST-1
        for i in range(10):
            assert disk.exists(f"$.FILE{i}")
        assert disk.exists("$.!BOOT")
        assert disk.exists("$.TEST-1")

        # A directory: FILE10-FILE19
        for i in range(10, 20):
            assert disk.exists(f"A.FILE{i}")

        # B directory: FILE20-FILE27, FILE31
        for i in range(20, 28):
            assert disk.exists(f"B.FILE{i}")


class TestFragmentedImage:
    """Tests for 03-fragmented.ssd (fragmentation test).

    Generator: tests/data/generators/03-fragmented.bas
    Format: 80-track SSD (204,800 bytes)
    Purpose: Test fragmentation detection and compaction

    Files created then FILEB and FILED deleted to create gaps:
    - FILEA (512 bytes, 2 sectors)
    - [GAP from deleted FILEB (768 bytes, 3 sectors)]
    - FILEC (512 bytes, 2 sectors)
    - [GAP from deleted FILED (1024 bytes, 4 sectors)]
    - FILEE (512 bytes, 2 sectors)
    - MARKER (created after deletions)
    """

    @pytest.fixture
    def disk(self, reference_image):
        return reference_image("03-fragmented.ssd")

    def test_surviving_files_after_deletions(self, disk):
        """Verify FILEA, FILEC, FILEE, MARKER remain (B and D deleted)."""
        assert disk.exists("$.FILEA")
        assert not disk.exists("$.FILEB")  # Deleted
        assert disk.exists("$.FILEC")
        assert not disk.exists("$.FILED")  # Deleted
        assert disk.exists("$.FILEE")
        assert disk.exists("$.MARKER")
        assert len(disk.files) == 4

    def test_file_sizes(self, disk):
        """Verify file sizes match generator specifications."""
        assert disk.get_file_info("$.FILEA").length == 512  # 2 sectors
        assert disk.get_file_info("$.FILEC").length == 512  # 2 sectors
        assert disk.get_file_info("$.FILEE").length == 512  # 2 sectors
        assert disk.get_file_info("$.MARKER").length > 0

    def test_fragmentation_detected(self, disk):
        """Verify free space is fragmented (multiple gaps exist)."""
        free_map = disk._catalogued_surface.get_free_map()
        # Should have multiple non-contiguous free regions from deleted files
        assert len(free_map) > 1, "Expected multiple fragmented free regions"

    def test_compaction_fills_gaps(self, writable_copy):
        """Verify compaction consolidates free space into single contiguous block."""
        disk, _ = writable_copy("03-fragmented.ssd")

        # Before compaction: multiple gaps
        free_map_before = disk._catalogued_surface.get_free_map()
        assert len(free_map_before) > 1, "Expected fragmentation before compaction"

        # Compact
        files_moved = disk.compact()
        assert files_moved > 0, "Expected files to be moved during compaction"

        # After compaction: single contiguous free region
        free_map_after = disk._catalogued_surface.get_free_map()
        assert len(free_map_after) == 1, "Expected single contiguous free block after compaction"


class TestDoubleSidedImage:
    """Tests for 04-double-sided.dsd (independent catalogs per side).

    Generator: tests/data/generators/04-double-sided.bas
    Format: 80-track DSD (409,600 bytes, interleaved)
    Purpose: Test double-sided disk with independent catalogs

    Side 0 (*DRIVE 0): 13 files
    - 5 small files (SMALL1-5, 1 sector each)
    - 3 medium files (MED1-3, 10 sectors each)
    - 5 files in directory A

    Side 1 (*DRIVE 2): 9 files
    - 3 large files (LARGE1-3, 20 sectors each)
    - 1 very large file (VLARGE, 50 sectors)
    - 5 files in directory B
    """

    @pytest.fixture
    def disk_side0(self, reference_image):
        return reference_image("04-double-sided.dsd", side=0)

    @pytest.fixture
    def disk_side1(self, reference_image):
        return reference_image("04-double-sided.dsd", side=1)

    def test_side0_file_count(self, disk_side0):
        """Verify side 0 contains 13 files."""
        assert len(disk_side0.files) == 13

    def test_side1_file_count(self, disk_side1):
        """Verify side 1 contains 9 files."""
        assert len(disk_side1.files) == 9

    def test_side0_small_files(self, disk_side0):
        """Verify side 0 has 5 small files (1 sector = 256 bytes each)."""
        for i in range(1, 6):
            assert disk_side0.exists(f"$.SMALL{i}")
            entry = disk_side0.get_file_info(f"$.SMALL{i}")
            assert entry.sectors == 1

    def test_side0_medium_files(self, disk_side0):
        """Verify side 0 has 3 medium files (10 sectors = 2560 bytes each)."""
        for i in range(1, 4):
            assert disk_side0.exists(f"$.MED{i}")
            entry = disk_side0.get_file_info(f"$.MED{i}")
            assert entry.sectors == 10

    def test_side1_large_files(self, disk_side1):
        """Verify side 1 has 3 large files (20 sectors = 5120 bytes each)."""
        for i in range(1, 4):
            assert disk_side1.exists(f"$.LARGE{i}")
            entry = disk_side1.get_file_info(f"$.LARGE{i}")
            assert entry.sectors == 20

    def test_side1_very_large_file(self, disk_side1):
        """Verify side 1 has 1 very large file (50 sectors = 12800 bytes)."""
        assert disk_side1.exists("$.HUGE")
        entry = disk_side1.get_file_info("$.HUGE")
        assert entry.sectors == 50

    def test_independent_catalogs(self, disk_side0, disk_side1):
        """Verify sides have completely independent catalogs."""
        # Sides have different file counts
        assert len(disk_side0.files) == 13
        assert len(disk_side1.files) == 9

        # Sides can have same filenames but different content (independent catalogs)
        # Verify at least one unique file per side to confirm independence
        side0_files = {f.filename for f in disk_side0.files}
        side1_files = {f.filename for f in disk_side1.files}

        # Side 0 should have unique files (like SMALL1-5, MED1-3)
        assert "SMALL1" in side0_files
        assert "SMALL1" not in side1_files

        # Side 1 should have unique files (like LARGE1-3, HUGE)
        assert "LARGE1" in side1_files
        assert "LARGE1" not in side0_files
        assert "HUGE" in side1_files
        assert "HUGE" not in side0_files

    def test_side0_directory_a(self, disk_side0):
        """Verify side 0 has 5 files in directory A."""
        a_files = [f for f in disk_side0.files if f.directory == "A"]
        assert len(a_files) == 5

    def test_side1_directory_b(self, disk_side1):
        """Verify side 1 has 5 files in directory B."""
        b_files = [f for f in disk_side1.files if f.directory == "B"]
        assert len(b_files) == 5

    def test_both_sides_accessible(self, disk_side0, disk_side1):
        """Verify both sides can be accessed independently."""
        # Both should have valid titles
        assert disk_side0.title.strip()
        assert disk_side1.title.strip()

        # Both should have non-zero file counts
        assert len(disk_side0.files) > 0
        assert len(disk_side1.files) > 0
